name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Platform
      run: rustup target install thumbv6m-none-eabi
    - name: Install Flip-link
      run: cargo install flip-link
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: rhythm-keyboard-rp2040
        # A file, directory or wildcard pattern that describes what to upload
        path: /target/thumbv6m-none-eabi/debug/rhythm-keyboard-rp2040
